name: Build

on:
  push:
    branches:
      - 'main'

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '23.x'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build Tailwind CSS
      run: make tailwind
    
    - name: Upload Artifacts
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: src/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
    - name: Deploy to Github Pages
      uses: actions/deploy-pages@v4