name: Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
    - name: Deploy to Github Pages
      uses: actions/deploy-pages@v4